// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Pustalorc.PlayerInfoLib.Unturned.Database;

namespace Pustalorc.PlayerInfoLib.Unturned.Migrations
{
    [DbContext(typeof(PlayerInfoLibDbContext))]
    internal partial class PlayerInfoLibDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pustalorc.PlayerInfoLib.Unturned.PlayerData", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("Id")
                    .HasColumnType("BIGINT UNSIGNED");

                b.Property<string>("CharacterName")
                    .IsRequired()
                    .HasColumnType("varchar(64)")
                    .HasMaxLength(64);

                b.Property<string>("Hwid")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long>("Ip")
                    .HasColumnType("bigint");

                b.Property<DateTime>("LastLoginGlobal")
                    .HasColumnType("datetime");

                b.Property<long>("LastQuestGroupId")
                    .HasColumnName("LastQuestGroupId")
                    .HasColumnType("BIGINT UNSIGNED");

                b.Property<int>("ServerId")
                    .HasColumnType("int");

                b.Property<long>("SteamGroup")
                    .HasColumnName("SteamGroup")
                    .HasColumnType("BIGINT UNSIGNED");

                b.Property<string>("SteamGroupName")
                    .IsRequired()
                    .HasColumnType("varchar(64)")
                    .HasMaxLength(64);

                b.Property<string>("SteamName")
                    .IsRequired()
                    .HasColumnType("varchar(64)")
                    .HasMaxLength(64);

                b.Property<double>("TotalPlaytime")
                    .HasColumnType("double");

                b.HasKey("Id");

                b.HasIndex("ServerId");

                b.ToTable("Pustalorc_PlayerInfoLib_Unturned_Players");
            });

            modelBuilder.Entity("Pustalorc.PlayerInfoLib.Unturned.Server", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Instance")
                    .IsRequired()
                    .HasColumnType("varchar(128)")
                    .HasMaxLength(128);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasMaxLength(50);

                b.HasKey("Id");

                b.ToTable("Pustalorc_PlayerInfoLib_Unturned_Servers");
            });

            modelBuilder.Entity("Pustalorc.PlayerInfoLib.Unturned.PlayerData", b =>
            {
                b.HasOne("Pustalorc.PlayerInfoLib.Unturned.Server", "Server")
                    .WithMany()
                    .HasForeignKey("ServerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}