name: Deployment

on: workflow_dispatch
jobs:
  deploy:
    name: "NuGet Deployment"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build PlayerInfoLib/PlayerInfoLib.csproj --configuration Release --no-restore
    - name: Push to NuGet
      run: dotnet nuget push PlayerInfoLib/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json
